version: "3"

services:
# postgresql
# ***************************************
  postgres:
    image: postgres:latest
    container_name: nx-nestjs-microservice-pg
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg/pgData:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - nx-nestjs-microservice
# rabbitmq 
# ***************************************
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - nx-nestjs-microservice
networks:
  nx-nestjs-microservice: